project:
  type: website

website:
  title: "Rich Ramsey"
  description: "Personal website of Richard Ramsey"
  site-url: https://richramsey.netlify.app/
  repo-url: https://github.com/rich-ramsey/blogdown3
  favicon: ./img/favicon.png
  navbar:
    logo: ./img/favicon.png
    background: dark
    foreground: light
    left:
      # - href: index.qmd
      #   text: Home
      - about.qmd
      - ./publications/publications.qmd
      - posts.qmd
      - ./resources/resources.qmd
      - ./soba_lab/soba-lab.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/RichRamseyPhD
        aria-label: twitter
        target: _blank
      - icon: mastodon
        href: https://twitter.com/RichRamseyPhD
        aria-label: mastodon
        target: _blank
      - text: "{{< ai google-scholar color=white >}}"
        href: https://scholar.google.com/citations?user=otXno0YAAAAJ&hl=en
        aria-label: google-scholar
        target: _blank
      - text: "{{< ai osf color=white >}}"
        href: https://osf.io/s67e2/
        aria-label: google-scholar
        target: _blank
      - icon: github
        href: https://github.com/rich-ramsey
        aria-label: GitHub
        target: _blank
      - icon: envelope
        href: mailto:richard.ramsey@hest.ethz.ch
        aria-label: envelope
      
        

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-title: "Contents"
    html-math-method: katex
    highlight-style: tango
    link-external-newwindow: true

editor: visual

