project:
  type: website
  render: 
    - "*.qmd"
    - "!publications_python.qmd"  ## Exclude the python script for generating pubs as it is redundant with the r version

website:
  title: "Rich Ramsey"
  description: "Personal website of Richard Ramsey"
  site-url: https://rich-ramsey.com
  repo-url: https://github.com/rich-ramsey/blogdown3
  favicon: ./img/favicon.png
  navbar:
    logo: ./img/favicon.png
    background: dark
    foreground: light
    left:
      # - href: index.qmd
      #   text: Home
      - about.qmd
      - ./publications/index.qmd
      - people.qmd
      - ./talks/index.qmd
      - posts.qmd
      - tutorials.qmd
      - resources.qmd
      - teaching.qmd
    right: 
      # - icon: twitter
      #   href: https://twitter.com/RichRamseyPhD
      #   aria-label: twitter
      #   target: _blank
      - icon: twitter
        href: https://bsky.app/profile/richramseyphd.bsky.social
        aria-label: twitter
        target: _blank
      - icon: mastodon
        href: https://mastodon.social/@richramsey
        aria-label: mastodon
        target: _blank
      - text: "{{< ai google-scholar color=white >}}"
        href: https://scholar.google.com/citations?user=otXno0YAAAAJ&hl=en
        aria-label: google-scholar
        target: _blank
      - text: "{{< ai orcid color=white >}}"
        href: https://orcid.org/0000-0002-0329-2112
        aria-label: orchid
        target: _blank
      - text: "{{< ai osf color=white >}}"
        href: https://osf.io/s67e2/
        aria-label: google-scholar
        target: _blank
      - icon: github
        href: https://github.com/rich-ramsey
        aria-label: GitHub
        target: _blank
      - icon: envelope
        href: mailto:richard.ramsey@hest.ethz.ch
        aria-label: envelope
  sidebar:
    - id: "about-sidebar"  # Default sidebar for most pages
      style: "floating"
      logo: ./img/favicon.png
      search: true
      
  page-footer:
    left: |
      {{< fa regular copyright >}} Richard Ramsey, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Plus help from [these fine folks](https://rich-ramsey.com/resources/resources.html#making-a-quarto-website)<br>
      [Source code at {{< fa brands github >}} GitHub](https://github.com/rich-ramsey/blogdown3)
      
      
format:
  html:
    theme: litera
    css: 
      - styles.css
      - custom.scss
    toc: true
    toc-title: "Contents"
    toc-mobile: true
    html-math-method: katex
    highlight-style: tango
    link-external-newwindow: true
        
editor_options: 
  type: source
  chunk_output_type: console
  markdown: 
    wrap: 72
    references:
      location: block
    canonical: true
  chunk: 
    tidy: true
    wrap: 80

