project:
  type: website

website:
  title: "Richard Ramsey"
  description: "Personal website of Richard Ramsey"
  # site-url: 
  repo-url: https://github.com/rich-ramsey/blogdown3
  favicon: /img/favicon.jpeg
  navbar:
    background: dark
    foreground: light
    left:
      # - href: index.qmd
      #   text: Home
      - about.qmd
      - publications.qmd
      - posts.qmd
      - resources.qmd
      - soba-lab.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

