---
title: "Resources"
---

Here is a list of useful resources that my lab has used in the last 5 years. These mainly focus on ways that we can try to improve the quality and transparency of scientific workflows.

## Things to read

This selection of journal papers and books provides a brief overview to Open Science and meta-science in general. Together, they motivate why the resources below have become an essential component to my lab's research.

-   Journal articles
    -   False positive psychology: [2011](https://doi.org/10.1177/0956797611417632)
    -   Scientific Utopia: [2012](http://pps.sagepub.com/cgi/content/abstract/7/6/615)
    -   Estimating reproducibility in psychology: [2015](http://www.sciencemag.org/content/349/6251/aac4716.abstract)
    -   A manifesto for reproducible science: [2017](http://dx.doi.org/10.1038/s41562-016-0021)
    -   Psychology's Renaissance: [2018](https://doi.org/10.1146/annurev-psych-122216-011836)
    -   Implications for scientific practice: [2018](http://journals.sagepub.com/doi/abs/10.1177/1745691617751884)
    -   Replicability, Robustness, and Reproducibility in Psychological Science: [2022](https://www.annualreviews.org/doi/abs/10.1146/annurev-psych-020821-114157)
-   Books
    -   The Seven Deadly Sins of Psychology: [2017](https://www.jstor.org/stable/j.ctvc779w5)
    -   Science Fictions: [2021](https://www.sciencefictions.org/)

## Data analysis

My lab has been inspired to adopt a Bayesian estimation approach to statistical analysis. The general workflow follows Richard McElreath's outstanding textbook and the translation into brms and Tidyverse by Solomon Kurz:

-   [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/) by Richard McElreath

-   And Solomon Kurz's [ebook](https://bookdown.org/content/3686/) version, which is also AMAZING!

Here are a bunch of other links to stats stuff that I've found really valuable to read:

-   Kruschke's [Doing Bayesian Data Analysis](https://sites.google.com/site/doingbayesiandataanalysis/)

-   [Kruschke & Liddell](https://link.springer.com/article/10.3758/s13423-016-1221-4). A good primer on the differences between frequentist and Bayesian analyses, as well as hypothesis testing and estimation approaches.

-   [Bodo Winter's book](https://bodowinter.com/books.html) is a great introduction to estimation approaches. It provides great R code for beginners and uses frequentist language, which should be more familiar to most. It is a great place to start and provides a natural platform to thinking about the same estimation approaches in a Bayesian context.

-   [brms](https://paul-buerkner.github.io/brms/) is a fabulous tool in R for running Bayesian analyses in STAN

-   Gigerenzer's [statistical rituals](https://journals.sagepub.com/doi/10.1177/2515245918771329) paper

-   On [statistical thinking](https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1518264) more generally

-   And why we need to do much more work before we think about running "tests" of hypotheses - [Scheel and co.](https://journals.sagepub.com/doi/10.1177/1745691620966795)

## Reproducible research

-   Version control in R. Renv: [link](https://rstudio.github.io/renv/articles/renv.html) and intro [video](https://www.youtube.com/watch?v=yjlEbIDevOs)

-   Version control using GitHub. Matti Vuorre and James P. Curley's excellent [tutorial](https://journals.sagepub.com/doi/full/10.1177/2515245918754826)

## Open Science Framework

-   A platform to support open science - [OSF](https://osf.io/) and intro [video](https://www.youtube.com/watch?v=X07mBq2tnMg&t=11s)

## Pre-registration

-   [aspredicted](https://aspredicted.org/)

-   [OSF registrations](https://help.osf.io/article/330-welcome-to-registrations)

-   [registered reports](https://www.cos.io/initiatives/registered-reports)

## Validity

-   A nice overview on four types of validity by [Simine Vazire and co.](https://journals.sagepub.com/doi/abs/10.1177/09637214211067779?journalCode=cdpa)

-   Why validity matters in experimental work in psychology and the importance of manipulation checks. [One](https://doi.org/10.1177/1745691620950684) and [Two](https://doi.org/10.1177/1745691620970602)

-   A fabulous empirical demonstration on the lack of relevant validity in a very well-cited social perception task - by Wendy Higgins and co. [here](https://doi.org/10.1177/10731911221124342) and [here](https://www.sciencedirect.com/science/article/pii/S014976342300057X)

## Making a Quarto website

I followed a whole bunch of posts to start a quarto website. Here are some that I found very helpful indeed.

-   [Drew Dimmery](https://ddimmery.com/posts/quarto-website/), especially for organising publications.

-   [Andreas Handel](https://www.andreashandel.com/posts/2022-10-01-hugo-to-quarto-migration/)

-   [Danielle Navarro](https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/)

-   [Albert Rapp](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html)

-   [Marvin Schmitt](https://www.marvinschmitt.com/blog/website-tutorial-quarto/)
